### ISSUE TITLE
(node:6628) DeprecationWarning

### ISSUE THREAD

**Issue by borodadada** [toBeTheLight/vue-ssr-learning#1]
(node:6628) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
server started at http://127.0.0.1:80

Hello, i have this warning.
Cool project (clear) but you miss css loader
`
{
        test: /\.css$/,
        use: [
          'vue-style-loader',
          {
            loader: 'css-loader',
            options: {
              modules: true,
              localIdentName: '[local]_[hash:base64:8]'
            }
          }
        ]
      },
`

**Comment by toBeTheLight** [comment]
@borodadada 
I have configured less-loader for less files. Maybe the warning is caused by using extract-text-webpack-plugin in webpack4 (having not seen your project, I guess). Having a try with mini-css-extract-plugin may be helpful.

**Comment by borodadada** [comment]
i dont have extract-text-webpack-plugin and mini-css-extract-plugin
this is my dependencies
https://image.ibb.co/b74Fxo/1.png

**Comment by toBeTheLight** [comment]
Hi @borodadada~.  [This will be solved in 2.6](https://github.com/vuejs/vue/pull/7839)
